### ISSUE TITLE
Github Actions vs. Containers

### ISSUE THREAD

**Issue by AdamMutzell** [Uplink036/PickleTestSuite#12]
Do research on what is the best way to change operating system

**Comment by Uplink036** [comment]
Github actions is a very interesting tool. First of all, we seem to be able to run linux(ubuntu in our case), mac and windows, see [this](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#excluding-a-version). 

Testing versions of python is also not a problem. Saving data and accessing data between runs is also possible, called [aritifats](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts).

This might spawn many runners however, which can be a problem. Especially if most of the time they run is spent on initialization and deletion, so more research on how [tox](https://tox.wiki/en/latest/) works is needed.

**Comment by Uplink036** [comment]
Tox is mostly set up now, therefore a workflow that will run tests on multiple environments is needed. We will still continue on with GitHub actions, but we'll make it a manual workflow, meaning it will only run when we trigger it, as i don't see it being needed so often.

**Comment by Uplink036** [comment]
Sadly, these couldn't be made as a branch beacuse it made for poor testing of the workflow. The workflow is now up and can be found [here](https://github.com/Uplink036/PickleTestSuite/blob/main/.github/workflows/testing.yml)
