### ISSUE TITLE
Add report template

### ISSUE THREAD

**Issue by AdamMutzell** [Uplink036/PickleTestSuite#6]
We need a report template for the project report. This will be good

**Comment by Uplink036** [comment]
It indeed "will be good". Do we think we can copy the  four points brought up in the description? E.g,.:
- Discusses your test suite, including applied strategies.
- Discusses the completeness of your test suite through a traceability matrix.
- Discusses the findings of your test suite.
- Discusses the limitations and shortcomings of your test suite.

Still unsure what the traceability matrix is, but hope that will be clarified soon.

**Comment by Uplink036** [comment]
Now that we know that traceability is not something we will be handling, we've got a report template up and working on it right now.
